java.lang.IllegalArgumentException: Invalid range specified (#7193)
This PR is handling situation when text range of autocomplete is invalid
(start offset is greater than end offset) which cause an error when
trying to display autocomplete for the user (ex.
[#3132](https://github.com/sourcegraph/jetbrains/issues/3132)). Change
aims to reduce bad UX and identify reason for incorrect ranges.
## Test plan
The changes made [here](https://github.com/sourcegraph/cody/pull/7162)
will provide some insight into the source of the incorrect text ranges.
<!-- Required. See
https://docs-legacy.sourcegraph.com/dev/background-information/testing_principles.
-->

---------

Co-authored-by: Tomasz Gołębiowski <tgolebiowski@virtuslab.com>