Add test case to reproduce crash that only happens with Enterprise accounts (#3055)
When triggering the "Document code" command in JetBrains with an
Enterprise account, we hit on the following error
```
InternalError: Cannot read properties of undefined (reading 'model')

TypeError: Cannot read properties of undefined (reading 'model')
    at getModel (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/models/index.ts:24:26)
    at Object.get (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/models/index.ts:47:13)
    at EditManager.executeEdit (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/edit/manager.ts:102:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5): {
  "error": {},
  "stack": "\nTypeError: Cannot read properties of undefined (reading 'model')\n    at getModel (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/models/index.ts:24:26)\n    at Object.get (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/models/index.ts:47:13)\n    at EditManager.executeEdit (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/edit/manager.ts:102:47)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
```

## Test plan
See added test case.
<!-- Required. See
https://sourcegraph.com/docs/dev/background-information/testing_principles.
-->