Agent: replace console.info with debug logs (#1234)
The console.info messages with \n were causing an error 
```
java.lang.IllegalStateException: Missing header Content-Length in input
```
replaced with the debug logger 
## Test plan
`./gradlew -PforceAgentBuild=true :runIDE`
Open a repo that does not have embeddings
ensure no error occurs.

<!-- Required. See
https://docs.sourcegraph.com/dev/background-information/testing_principles.
-->