Bring back missing action description (#1891)
Rel: https://github.com/sourcegraph/jetbrains/pull/1872

## The error

```
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key action.sourcegraph.disabled.description
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at com.sourcegraph.common.CodyBundle.getString(CodyBundle.kt:29)
	at com.sourcegraph.cody.chat.actions.BaseChatAction.update(BaseChatAction.kt:31)
```

## Test plan

I am not sure. I was testing my own branch and I encountered the error.