swallow showPopover exception
Some users reported that clicking the model selector in chat would cause the chat webview to go blank and show an exception:

```
DOMException: Failed to execute 'showPopover' on 'HTMLElement': Invalid on popover elements which aren't hidden.
```