Improve logic for applying auto-edits (#8043)
## Changes

This PR ensures that when showing auto-edits we do not trust range
provided by agent alone, but instead we check if the "diff" is matching.

Among other issues it should fix this `IndexOutOfBoundsException` issue:

```
java.lang.IndexOutOfBoundsException: Range [2967, 2966) out of bounds for length 2966
	at java.base/jdk.internal.util.Preconditions$3.apply(Preconditions.java:71)
	at java.base/jdk.internal.util.Preconditions$3.apply(Preconditions.java:68)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:684)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:218)
	at kotlin.text.StringsKt__StringsKt.replaceRange(Strings.kt:521)
	at kotlin.text.StringsKt__StringsKt.replaceRange(Strings.kt:541)
	at com.sourcegraph.cody.autoedit.AutoeditManager.showAutoedit(AutoeditManager.kt:56)
	at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.processAutocompleteResult$lambda$11$lambda$9(CodyAutocompleteManager.kt:221)
	at com.intellij.openapi.application.ActionsKt.runInEdt(actions.kt:48)
	at com.intellij.openapi.application.ActionsKt.runInEdt$default(actions.kt:45)
	at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.processAutocompleteResult$lambda$11(CodyAutocompleteManager.kt:218)
```

It also slightly improves the way diff ranges are rendered.

### Before:
![Pasted Graphic
3](https://github.com/user-attachments/assets/e307bb21-7680-43e8-ad31-99a4edc0a94f)

### After:
![Pasted
Graphic](https://github.com/user-attachments/assets/1072bc1f-4de5-4fa9-9613-9d45ad5b3725)
![Pasted Graphic
4](https://github.com/user-attachments/assets/e772eac6-d285-4f2e-a6fc-c7989fdecdf0)
![Pasted Graphic
2](https://github.com/user-attachments/assets/932dffbc-031d-4a30-ba3c-53b67614d097)


## Test plan

1. Add `"cody.suggestions.mode": "auto-edit",` entry to the
`cody_settings.json`
2. Open some existing project file
3. Remove bodies of few methods
4. Type space or hit enter in a body of the first removed method 
5. Cody should render auto-edit diff, accept it with tab
6. Cody should render another diff in the next method with removed body

That is not deterministic test, but in most cases it allows to test
tab-tab-tab edit workflows.

<!-- Required. See
https://docs-legacy.sourcegraph.com/dev/background-information/testing_principles.
-->